plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id 'net.darkhax.curseforgegradle'
}

repositories {
    exclusiveContent {
        forRepositories(
            maven {
                name = 'Ladysnake'
                url = 'https://maven.ladysnake.org/releases'
            }
        )
        filter {
            includeGroupAndSubgroups('org.ladysnake')
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    modImplementation "mysticdrew:common-networking-fabric:${common_networking_version}"
    modImplementation "dev.upcraft.sparkweave:Sparkweave-Fabric:${sparkweave_version}"

    modImplementation "org.ladysnake.cardinal-components-api:cardinal-components-base:${project.cardinal_components_api_version}"
    modImplementation "org.ladysnake.cardinal-components-api:cardinal-components-entity:${project.cardinal_components_api_version}"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

tasks.register('publishCurseForge', net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    dependsOn(remapJar)
    apiToken = findProperty('cf_api_token')
    // The main file to upload
    def mainFile = upload(1373587, remapJar)
    mainFile.withAdditionalFile(remapSourcesJar)
    mainFile.displayName = "Scryers-fabric-${minecraft_version}-${version}"
    mainFile.releaseType = "${releasetype}"
    mainFile.changelog = "${changelog}"
    mainFile.changelogType = 'markdown'
    mainFile.addGameVersion("${minecraft_version}")
    mainFile.addGameVersion("fabric")

    mainFile.addRequirement("cardinal-components-api")
    mainFile.addRequirement("common-network")
    mainFile.addRequirement("sparkweave")
}
